import type { Pool } from 'pg';
import type { DdlRequest } from '@shared/ipc';
import { qualify, quoteIdent, quoteLiteral } from './quote';

/**
 * Builds a complete, runnable DDL script for a catalog object.
 * Every lookup is parameterised ($n) and every identifier is emitted through
 * pg-format `%I` (client) or `format('%I')` / `quote_ident` (server). No raw interpolation.
 */
export async function getDdl(pool: Pool, req: DdlRequest): Promise<string> {
  switch (req.kind) {
    case 'table':
      return tableDdl(pool, requireSchema(req), req.name);
    case 'view':
    case 'matview':
      return viewDdl(pool, requireSchema(req), req.name);
    case 'index':
      return indexDdl(pool, requireSchema(req), req.name);
    case 'trigger':
      return triggerDdl(pool, requireSchema(req), requireParent(req), req.name);
    case 'constraint':
      return constraintDdl(pool, requireSchema(req), requireParent(req), req.name);
    case 'column':
      return columnDdl(pool, requireSchema(req), requireParent(req), req.name);
    case 'function':
      return functionDdl(pool, requireSchema(req), req.name);
    case 'schema':
      return schemaDdl(pool, req.name);
    default:
      throw new Error(`Unsupported DDL kind: ${String((req as DdlRequest).kind)}`);
  }
}

function requireSchema(req: DdlRequest): string {
  if (!req.schema) throw new Error(`DDL for ${req.kind} requires a schema`);
  return req.schema;
}

function requireParent(req: DdlRequest): string {
  if (!req.parent) throw new Error(`DDL for ${req.kind} requires a parent table`);
  return req.parent;
}

interface RelationRow {
  oid: number;
  relkind: string;
  comment: string | null;
  partkey: string | null;
  server: string | null;
}

async function findRelation(pool: Pool, schema: string, name: string, kinds: string[]): Promise<RelationRow> {
  const { rows } = await pool.query<RelationRow>(
    `SELECT c.oid,
            c.relkind,
            obj_description(c.oid, 'pg_class') AS comment,
            CASE WHEN c.relkind = 'p' THEN pg_get_partkeydef(c.oid) END AS partkey,
            (SELECT s.srvname FROM pg_foreign_table ft JOIN pg_foreign_server s ON s.oid = ft.ftserver
              WHERE ft.ftrelid = c.oid) AS server
       FROM pg_class c
       JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = $1 AND c.relname = $2 AND c.relkind = ANY($3::"char"[])`,
    [schema, name, kinds]
  );
  const row = rows[0];
  if (!row) throw new Error(`Relation ${schema}.${name} not found`);
  return row;
}

interface ColumnRow {
  attname: string;
  type: string;
  notnull: boolean;
  default: string | null;
  generated: string;
  identity: string;
  collation: string | null;
  comment: string | null;
}

async function columnsOf(pool: Pool, oid: number): Promise<ColumnRow[]> {
  const { rows } = await pool.query<ColumnRow>(
    `SELECT a.attname,
            format_type(a.atttypid, a.atttypmod) AS type,
            a.attnotnull AS notnull,
            pg_get_expr(d.adbin, d.adrelid) AS "default",
            a.attgenerated AS generated,
            a.attidentity AS identity,
            CASE WHEN a.attcollation <> t.typcollation AND a.attcollation <> 0
                 THEN (SELECT quote_ident(cn.nspname) || '.' || quote_ident(co.collname)
                         FROM pg_collation co JOIN pg_namespace cn ON cn.oid = co.collnamespace
                        WHERE co.oid = a.attcollation) END AS collation,
            col_description(a.attrelid, a.attnum) AS comment
       FROM pg_attribute a
       JOIN pg_type t ON t.oid = a.atttypid
       LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
      WHERE a.attrelid = $1 AND a.attnum > 0 AND NOT a.attisdropped
      ORDER BY a.attnum`,
    [oid]
  );
  return rows;
}

function columnDefinition(c: ColumnRow): string {
  const parts = [quoteIdent(c.attname), c.type];
  if (c.collation) parts.push(`COLLATE ${c.collation}`);
  if (c.notnull) parts.push('NOT NULL');
  if (c.generated === 's' && c.default) {
    parts.push(`GENERATED ALWAYS AS (${c.default}) STORED`);
  } else if (c.identity === 'a') {
    parts.push('GENERATED ALWAYS AS IDENTITY');
  } else if (c.identity === 'd') {
    parts.push('GENERATED BY DEFAULT AS IDENTITY');
  } else if (c.default) {
    parts.push(`DEFAULT ${c.default}`);
  }
  return parts.join(' ');
}

interface ConstraintRow {
  conname: string;
  contype: string;
  definition: string;
}

async function constraintsOf(pool: Pool, oid: number): Promise<ConstraintRow[]> {
  const { rows } = await pool.query<ConstraintRow>(
    `SELECT conname, contype, pg_get_constraintdef(oid, true) AS definition
       FROM pg_constraint
      WHERE conrelid = $1
      ORDER BY CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2 WHEN 'f' THEN 3 ELSE 4 END, conname`,
    [oid]
  );
  return rows;
}

interface IndexRow {
  indexname: string;
  definition: string;
}

/** Indexes that are not backing a constraint (those are covered by ADD CONSTRAINT). */
async function nonConstraintIndexesOf(pool: Pool, oid: number): Promise<IndexRow[]> {
  const { rows } = await pool.query<IndexRow>(
    `SELECT ic.relname AS indexname, pg_get_indexdef(i.indexrelid) AS definition
       FROM pg_index i
       JOIN pg_class ic ON ic.oid = i.indexrelid
      WHERE i.indrelid = $1
        AND NOT EXISTS (SELECT 1 FROM pg_constraint co WHERE co.conindid = i.indexrelid AND co.contype IN ('p','u','x'))
      ORDER BY ic.relname`,
    [oid]
  );
  return rows;
}

interface TriggerRow {
  tgname: string;
  definition: string;
}

async function triggersOf(pool: Pool, oid: number): Promise<TriggerRow[]> {
  const { rows } = await pool.query<TriggerRow>(
    `SELECT tgname, pg_get_triggerdef(oid, true) AS definition
       FROM pg_trigger
      WHERE tgrelid = $1 AND NOT tgisinternal
      ORDER BY tgname`,
    [oid]
  );
  return rows;
}

function commentStatements(kind: string, target: string, comment: string | null): string[] {
  return comment ? [`COMMENT ON ${kind} ${target} IS ${quoteLiteral(comment)};`] : [];
}

async function tableDdl(pool: Pool, schema: string, name: string): Promise<string> {
  const rel = await findRelation(pool, schema, name, ['r', 'p', 'f']);
  const q = qualify(schema, name);
  const [columns, constraints, indexes, triggers] = await Promise.all([
    columnsOf(pool, rel.oid),
    constraintsOf(pool, rel.oid),
    nonConstraintIndexesOf(pool, rel.oid),
    triggersOf(pool, rel.oid)
  ]);

  const lines: string[] = [];
  const head = rel.relkind === 'f' ? 'CREATE FOREIGN TABLE' : 'CREATE TABLE';
  lines.push(`${head} ${q} (`);
  lines.push(columns.map((c) => `  ${columnDefinition(c)}`).join(',\n'));
  const tail: string[] = [')'];
  if (rel.relkind === 'p' && rel.partkey) tail.push(`PARTITION BY ${rel.partkey}`);
  if (rel.relkind === 'f' && rel.server) tail.push(`SERVER ${quoteIdent(rel.server)}`);
  lines.push(`${tail.join(' ')};`);

  const sections: string[] = [lines.join('\n')];
  if (constraints.length) {
    sections.push(
      constraints.map((c) => `ALTER TABLE ${q} ADD CONSTRAINT ${quoteIdent(c.conname)} ${c.definition};`).join('\n')
    );
  }
  if (indexes.length) sections.push(indexes.map((i) => `${i.definition};`).join('\n'));
  const comments = [
    ...commentStatements('TABLE', q, rel.comment),
    ...columns.flatMap((c) => commentStatements('COLUMN', `${q}.${quoteIdent(c.attname)}`, c.comment))
  ];
  if (comments.length) sections.push(comments.join('\n'));
  if (triggers.length) sections.push(triggers.map((t) => `${t.definition};`).join('\n'));
  return sections.join('\n\n') + '\n';
}

async function viewDdl(pool: Pool, schema: string, name: string): Promise<string> {
  const rel = await findRelation(pool, schema, name, ['v', 'm']);
  const q = qualify(schema, name);
  const { rows } = await pool.query<{ def: string }>('SELECT pg_get_viewdef($1::oid, true) AS def', [rel.oid]);
  const def = rows[0]?.def ?? '';
  const head = rel.relkind === 'm' ? 'CREATE MATERIALIZED VIEW' : 'CREATE VIEW';
  const sections: string[] = [`${head} ${q} AS\n${def.trim().replace(/;\s*$/, '')};`];
  const columns = await columnsOf(pool, rel.oid);
  const comments = [
    ...commentStatements(rel.relkind === 'm' ? 'MATERIALIZED VIEW' : 'VIEW', q, rel.comment),
    ...columns.flatMap((c) => commentStatements('COLUMN', `${q}.${quoteIdent(c.attname)}`, c.comment))
  ];
  if (comments.length) sections.push(comments.join('\n'));
  if (rel.relkind === 'm') {
    const indexes = await nonConstraintIndexesOf(pool, rel.oid);
    if (indexes.length) sections.push(indexes.map((i) => `${i.definition};`).join('\n'));
  }
  return sections.join('\n\n') + '\n';
}

async function indexDdl(pool: Pool, schema: string, name: string): Promise<string> {
  const { rows } = await pool.query<{ def: string }>(
    `SELECT pg_get_indexdef(c.oid) AS def
       FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = $1 AND c.relname = $2 AND c.relkind IN ('i','I')`,
    [schema, name]
  );
  const def = rows[0]?.def;
  if (!def) throw new Error(`Index ${schema}.${name} not found`);
  return `${def};\n`;
}

async function triggerDdl(pool: Pool, schema: string, table: string, name: string): Promise<string> {
  const { rows } = await pool.query<{ def: string }>(
    `SELECT pg_get_triggerdef(t.oid, true) AS def
       FROM pg_trigger t
       JOIN pg_class c ON c.oid = t.tgrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = $1 AND c.relname = $2 AND t.tgname = $3 AND NOT t.tgisinternal`,
    [schema, table, name]
  );
  const def = rows[0]?.def;
  if (!def) throw new Error(`Trigger ${name} on ${schema}.${table} not found`);
  return `${def};\n`;
}

async function constraintDdl(pool: Pool, schema: string, table: string, name: string): Promise<string> {
  const { rows } = await pool.query<{ def: string }>(
    `SELECT pg_get_constraintdef(co.oid, true) AS def
       FROM pg_constraint co
       JOIN pg_class c ON c.oid = co.conrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = $1 AND c.relname = $2 AND co.conname = $3`,
    [schema, table, name]
  );
  const def = rows[0]?.def;
  if (!def) throw new Error(`Constraint ${name} on ${schema}.${table} not found`);
  return `ALTER TABLE ${qualify(schema, table)} ADD CONSTRAINT ${quoteIdent(name)} ${def};\n`;
}

async function columnDdl(pool: Pool, schema: string, table: string, name: string): Promise<string> {
  const rel = await findRelation(pool, schema, table, ['r', 'p', 'f', 'v', 'm']);
  const column = (await columnsOf(pool, rel.oid)).find((c) => c.attname === name);
  if (!column) throw new Error(`Column ${name} on ${schema}.${table} not found`);
  const q = qualify(schema, table);
  const parts = [`ALTER TABLE ${q} ADD COLUMN ${columnDefinition(column)};`];
  parts.push(...commentStatements('COLUMN', `${q}.${quoteIdent(name)}`, column.comment));
  return parts.join('\n') + '\n';
}

async function functionDdl(pool: Pool, schema: string, name: string): Promise<string> {
  const { rows } = await pool.query<{ def: string }>(
    `SELECT pg_get_functiondef(p.oid) AS def
       FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = $1 AND p.proname = $2 AND p.prokind IN ('f','p')
      ORDER BY p.oid`,
    [schema, name]
  );
  if (!rows.length) throw new Error(`Function ${schema}.${name} not found`);
  return rows.map((r) => `${r.def.trim()};`).join('\n\n') + '\n';
}

async function schemaDdl(pool: Pool, name: string): Promise<string> {
  const { rows } = await pool.query<{
    owner: string;
    comment: string | null;
    tables: string;
    views: string;
    functions: string;
  }>(
    `SELECT pg_get_userbyid(n.nspowner) AS owner,
            obj_description(n.oid, 'pg_namespace') AS comment,
            (SELECT count(*) FROM pg_class c WHERE c.relnamespace = n.oid AND c.relkind IN ('r','p','f'))::text AS tables,
            (SELECT count(*) FROM pg_class c WHERE c.relnamespace = n.oid AND c.relkind IN ('v','m'))::text AS views,
            (SELECT count(*) FROM pg_proc p WHERE p.pronamespace = n.oid)::text AS functions
       FROM pg_namespace n
      WHERE n.nspname = $1`,
    [name]
  );
  const row = rows[0];
  if (!row) throw new Error(`Schema ${name} not found`);
  const lines = [
    `-- ${row.tables} tables, ${row.views} views, ${row.functions} functions`,
    `CREATE SCHEMA ${quoteIdent(name)} AUTHORIZATION ${quoteIdent(row.owner)};`,
    ...commentStatements('SCHEMA', quoteIdent(name), row.comment)
  ];
  return lines.join('\n') + '\n';
}
