import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { CircleAlert } from 'lucide-react';
import type { FieldInfo } from '@shared/types/query';
import { setEditorContext } from '@renderer/features/editor/editorRegistry';
import { refreshDocLinks } from '@renderer/features/editor';
import { useStore } from '@renderer/store';
import { draftToJsonText, parseDraft, type Row } from './documentModel';

const MonacoJsonEditor = lazy(() => import('@renderer/features/editor/MonacoJsonEditor'));

export interface JsonEditorViewProps {
  tabId: string;
  connectionId: string;
  database: string;
  fields: FieldInfo[];
  original: Row;
  draft: Row;
  onDraft(next: Row): void;
  onError(message: string | null): void;
}

type EditorLike = {
  createDecorationsCollection(decos: Array<{ range: { startLineNumber: number; startColumn: number; endLineNumber: number; endColumn: number }; options: { inlineClassName?: string; isWholeLine?: boolean; hoverMessage?: { value: string } } }>): { clear(): void; set(d: unknown[]): void };
  getModel(): { getLineCount(): number; getLineContent(n: number): string } | null;
  onDidChangeModelContent(cb: () => void): { dispose(): void };
};

/** Raw JSON of the whole row in Monaco; `_id` gets a read-only decoration and is never changed by parsing. */
export function JsonEditorView(p: JsonEditorViewProps): JSX.Element {
  const [error, setError] = useState<string | null>(null);
  const text = useMemo(() => draftToJsonText(p.draft, p.fields), [p.draft, p.fields]);
  const modelKey = `${p.tabId}:json`;
  const editorRef = useRef<EditorLike | null>(null);

  useEffect(() => {
    setEditorContext(modelKey, { connectionId: p.connectionId, database: p.database, tabId: p.tabId });
    return () => setEditorContext(modelKey, undefined);
  }, [modelKey, p.connectionId, p.database, p.tabId]);

  // Whether a reference resolves is decided against the catalog index, which loads lazily.
  // Load it for this database and recompute links once it arrives, otherwise an editor opened
  // first shows no links at all until its text changes.
  const indexReady = useStore((st) => Boolean(st.completionIndex[`${p.connectionId}/${p.database}`]));
  useEffect(() => {
    void useStore.getState().ensureCompletionIndex(p.connectionId, p.database);
  }, [p.connectionId, p.database]);
  useEffect(() => {
    if (indexReady) refreshDocLinks();
  }, [indexReady]);

  const onChange = useCallback(
    (v: string) => {
      const r = parseDraft(v, p.fields, p.original);
      if ('error' in r) {
        setError(r.error);
        p.onError(r.error);
        return;
      }
      setError(null);
      p.onError(null);
      p.onDraft(r.draft);
    },
    [p]
  );

  const decorate = useCallback((ed: EditorLike) => {
    editorRef.current = ed;
    const apply = (): void => {
      const model = ed.getModel();
      if (!model) return;
      const n = model.getLineCount();
      for (let i = 1; i <= n; i++) {
        if (/^\s*"_id"\s*:/.test(model.getLineContent(i))) {
          ed.createDecorationsCollection([
            {
              range: { startLineNumber: i, startColumn: 1, endLineNumber: i, endColumn: model.getLineContent(i).length + 1 },
              options: { isWholeLine: true, inlineClassName: 'opacity-60', hoverMessage: { value: '`_id` is generated by the database and read-only' } }
            }
          ]);
          return;
        }
      }
    };
    apply();
    ed.onDidChangeModelContent(apply);
  }, []);

  return (
    <div className="relative flex h-full min-h-0 flex-col">
      {error && (
        <div className="flex items-center gap-2 border-b border-destructive/40 bg-destructive/10 px-3 py-1 text-[12px] text-destructive">
          <CircleAlert size={13} strokeWidth={1.75} /> {error}
        </div>
      )}
      <div className="min-h-0 flex-1">
        <Suspense fallback={<div className="p-3 text-[12px] text-muted-foreground">Loading editor…</div>}>
          <MonacoJsonEditor modelKey={modelKey} value={text} onChange={onChange} onMount={(ed) => decorate(ed as unknown as EditorLike)} />
        </Suspense>
      </div>
    </div>
  );
}
